#!/bin/bash
set -e

[ -n "$CLEAN" ] && swift package clean
swift build -Xcc -I/usr/local/include -Xcc -I/usr/local/Cellar/openssl/1.0.2j/include -Xlinker -L/usr/local/lib/ -Xlinker -L/usr/local/Cellar/openssl/1.0.2j/lib/ 2>&1 | while read -r line; do
  if echo "$line" | grep -q "error: "; then
    failed=1
    echo -e "\033[31m$line\033[0m"
    continue
  fi
  if echo "$line" | grep -q "warning: "; then
    echo -e "\033[1;37m$line\033[0m"
    continue
  fi
  echo "$line"
done

exit 0
